config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  # We create the register route manually because we don't want the URl to be /users/new as would be w/ resources
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # expose all post related routes except delete
  resources :posts, except: [:destroy] do
    # /post/2/vote => posts#vote
    member do
      post 'vote'
    end
    
    resources :comments, only: [:create] do
      member do
        # posts/3/comments/1/vote => comments#vote
        # vote_post_comment
        # NOTE: Must pass in post AND comment in view
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  
  # Exclude new as we create manually above
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  has_many :votes, as: :voteable

  validates :body, presence: true

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  # Business logic goes here in the model
  # Presentation stuff goes in the helpers
  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  # on: :create means it only fires for a new registration, not an update
  validates :password, presence: true, on: :create, length: { minimum: 4 }
end
 

app/models/vote.rb
class Vote < ActiveRecord::Base
  # class_name and foreign_key are necessary because "creator" deviates from the default of user
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

  # Same user can't create a vote for the same object
  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Methods here available in all controllers

  # Make these helpers available to the views not just the controllers
  helper_method :current_user, :logged_in?

  def current_user
    # ||= (memoization) - don't run if @current_user exists already in current view
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    
    if @category.save
        flash[:notice] = "Your category was created."
        redirect_to root_path
      else
        render :new
      end
  end

  private
  # Parse the attributes we want to mass assign out of the params hash using strong parameters
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @post = Post.find(params[:post_id])
    comment_params = params.require(:comment).permit(:body)
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      # Redirect to post's show page
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    comment = Comment.find(params[:id])
    vote = Vote.create(voteable: comment, creator: current_user, vote: params[:vote])
    
    if vote.valid?
      flash[:notice] = 'Your vote was counted.'
    else
      flash[:error] = 'You can only vote on a comment once.'
    end

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
        # flash[:notice] = "Your post was created."
        redirect_to posts_path, notice: "Your post was created."
      else
        render :new
      end
  end

  def edit; end

  def update
    if @post.update(post_params)
        flash[:notice] = "Your post was updated."
        redirect_to post_path
      else
        render :edit
      end
  end

  def vote
    vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    if vote.valid?
      flash[:notice] = 'Your vote was counted.'
    else
      flash[:error] = 'You can only vote on a post once.'
    end
    
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    # Permit title, url, description params only
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.where(username: params[:username]).first
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've logged in."
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]
  
def show
  
end

  # Register a new users at /register
  def new
    @user = User.new
  end

  # Handle submission of new registration
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user[:id]
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was upddated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You cannot do that."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def display_datetime(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z") #03/14/2013 9:09pm
  end
end

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-primary"><%= link_to category.name, category_path(category), class: "text-white" %></span>

app/views/categories/new.html.erb
<%= render '/shared/content_title', title: 'Create a new category' %>

<%= render '/shared/error', object: @category %>

<div class="card">
  <div class="card-body">
    <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'Create Category', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% header = "#{link_to('All Posts', posts_path)} &raquo; #{@category.name}".html_safe %>

<%= render '/shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation-new.html copy.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <%= link_to "Postit!", root_path, :class => 'navbar-brand' %>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% Category.all.each do |category| %>
          <%= link_to category.name, category_path(category), class: "dropdown-item" %>
        <% end %>
        <% if logged_in? %>
          <div class="dropdown-divider"></div>
          <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
    <% if logged_in? %>
      <%# User menu %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
          <%= link_to "edit profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "view profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "log out", logout_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="ml-2"><%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %></li>
      <li class="ml-2"><%= link_to 'Log out', logout_path, class: 'btn btn-primary btn-small' %></li>
    <% else %>
    <li class="ml-2"><%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %></li>
      <li class="ml-2"><%= link_to 'Log in', login_path, class: 'btn btn-primary btn-small ' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <%= link_to "Postit!", root_path, :class => 'navbar-brand' %>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% Category.all.each do |category| %>
          <%= link_to category.name, category_path(category), class: "dropdown-item" %>
        <% end %>

        <% if logged_in? %>
          <div class="dropdown-divider"></div>
          <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
    <% if logged_in? %>
    <%# User menu %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
          <%= link_to "edit profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "view profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "log out", logout_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="ml-2"><%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %></li>
      <li class="ml-2"><%= link_to 'Logout', logout_path, class: 'btn btn-danger btn-small' %></li>
    <% else %>
      <li class="ml-2"><%= link_to 'Login', login_path, class: 'btn btn-small' %></li>
      <li class="ml-2"><%= link_to 'Register', register_path, class: 'btn btn-small' %></li>
    <% end %>
    
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostitUpdated</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>  
    </header>
    <div id="main" role="main">
      <div class="container">
        
        <%= render 'layouts/messages' %>
        <%= yield %>
  
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_comment.html.erb
<%# if show_post is not passed in, set it to false (so you only need to pass it in if you want to show post) %>
<% show_post ||= false %>

<div class="row">
  <div class="col-2">
    <div class="card">
      <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
            <% if logged_in? %>
              up
            <% end %>
          <% end %>
        <%= "#{comment.total_votes} vote#{comment.total_votes != 1 ? 's' : ''}" %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
          <% if logged_in? %>
              down
            <% end %>
        <% end %>        
      </div>
    </div>
  </div>
  
  <div class="col-10">
    <div class="card">
      <div class="card-body">
        <em>"<%= comment.body %>"</em>
        <% if show_post %>
          <span>on <%= link_to comment.post.title, post_path(comment.post) %></span>
        <% end %>
        <br />
        <span class="quiet">by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
        <span>at <%= display_datetime(comment.created_at) %></span>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render '/shared/error', object: @post %>

<div class="card">
  <div class="card-body">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 5, class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="mb-1">Categories</div>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <div class="form-check form-check-inline">
            <%= cb.label(class: "form-check-label") {cb.check_box(class: "form-check-input") + cb.text} %>
          </div>
        <% end %>
      </div>
      <%= f.submit @post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-2">
    <div class="card">
      <div class="card-body d-flex flex-column justify-content-center align-items-center">
        <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
          <% if logged_in? %>
              <div>up</div>
            <% end %>
        <% end %>
        <%# Instance method in the Post model %>
        <%= "#{post.total_votes} vote#{post.total_votes != 1 ? 's' : ''}" %>
        <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
          <% if logged_in? %>
              <div>down</div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-10">
    <div class="card">
      <div class="card-body">
        <%# Rendering a partial with a collection - like post.categories.each do |category| render 'categories/_category', category: category %>
        <div class="card-title"><%= render post.categories %></div>
        <h4><%= link_to post.title, fix_url(post.url) %></h4>
        <p><%= post.description %></p>
        <p>
          <span class="quiet">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
          <span>at <%= display_datetime(post.created_at) %></span>
        </p>
        <small>
          <span>
            <%= link_to "#{post.comments.size} comments", post_path(post) %>
          </span>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit your post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <%= render 'shared/content_title', title: "All Posts" %>

  <hr>

  <% @posts.each do |post| %>
    <%= render 'post', post: post%>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a New Post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to 'edit this post', edit_post_path(@post)%>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<hr />

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %> <%# Submit to /posts/3/comments %>
  <%= render 'shared/error', object: @comment %>
    <div class="form-group">
      <%= f.label :body, "Leave a comment" %>
      <%= f.text_area :body, rows: 3, class: 'form-control' %>
    </div>
    <%= f.submit 'Create a comment', class: 'btn btn-primary'%>
  <% end %>
<% end %>

<div class="mt-4">
  <h5>Comments</h5>
  <ul>
    <% @post.comments.each do |comment| %>
      <%= render 'comment', comment: comment %>
    <% end %>
  </ul>
</div>

app/views/shared/_content_title.html.erb
<p class="mt-3">
  <%= title %>
  <hr />
</p>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h4>Please fix the following errors:</h4>
    <ul class="list-group">
      <% object.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%# @TODO if i use new syntax "form_with", errors won't register - i think User.new is called in the new action before this renders which wipes out error hash %>

<%= render '/shared/error', object: @user%>

<div class="card">
  <div class="card-body">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f. text_field :username, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f. password_field :password, class: "form-control"%>
      </div>
      <%= f.submit @user.new_record? ? 'Register' : 'Update', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render '/shared/content_title', title: "Update your profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render '/shared/content_title', title: "Register"%>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "#{@user.username}'s profile" %>

<div class="card mb-4">
  <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Username</dt>
      <dd class="col-sm-9"><%= @user.username %></dd>
    </div>
  </div>
</dl>

<div>
  <h5><%= "#{@user.username}'s activity" %></h5>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "Posts (#{@user.posts.size})", user_path(@user), class: "nav-link #{'active' if params[:tab].nil?}" %>
    </li>
    <li class="nav-item">
      <%# Add to params hash by specifying a 2nd arg in the path %>
      <%# Params hash is accessible in the view, so we can conditinoally add a class here and above based on what tab has been clicked %>
      <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments'), class: "nav-link #{'active' if params[:tab] == 'comments'}" %>
    </li>
  </ul>
</div>

<div>
  <% if params[:tab].nil? %>
    <% @user.posts.each do |post| %>
      <%= render 'posts/post', post: post %>
    <% end %>
  <% else %>
    <% @user.comments.each do |comment| %>
      <%# <%= render partial: 'posts/comment', locals: { comment: comment, show_post: true } %>
      <%= render 'posts/comment',  comment: comment, show_post: true %>
    <% end %>
  <% end %>
</div>